name = "LocalApproximationValueIteration"
uuid = "a40420fb-f401-52da-a663-f502e5b95060"
repo = "https://github.com/JuliaPOMDP/LocalApproximationValueIteration.jl"
version = "0.4.3"

[deps]
LocalFunctionApproximation = "db97f5ab-fc25-52dd-a8f9-02a257c35074"
POMDPLinter = "f3bd98c0-eb40-45e2-9eb1-f2763262d755"
POMDPTools = "7588e00f-9cae-40de-98dc-e0c70c48cdd7"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
LocalFunctionApproximation = "1.1"
POMDPLinter = "0.1"
POMDPTools = "0.1, 1"
POMDPs = "0.9, 1"
julia = "1"
